### ISSUE TITLE
Using SocketHandler

### ISSUE THREAD

**Issue by sr-gi** [nralbers/structlog-extensions-nralbers#4]
Hey Neils, this is more of a question than an actual issue.

I'm wondering is there is any way of using the structlog-extension using `SocketHandler` instead of `StreamHandler`. I've adapted part of the code to use it but looks like that data that is being sent over the socket is not maintaining the structlog format, only the message is being sent instead.

**Comment by nralbers** [comment]
Hi there,
You're probably better off asking this question on the structlog issue tracker. All these extensions are are a plugin processors. The actual logging heavy lifting is being done by the structlog library itself.
My guess (and it is just that, I haven't checked) is that the Sockethandler doesn't allow for formatting. Since you're trying to output in json format, and the formatting is done by the StreamHandler, this is failing.

**Comment by nralbers** [comment]
Just checked the config again. This is actually being done by the logging library. 
To be clear, the config example given is leveraging not only this library, but structlog and the python standard logging library.

**Comment by sr-gi** [comment]
> My guess (and it is just that, I haven't checked) is that the Sockethandler doesn't allow for formatting.

Actually you were right. `SocketHandler` does not allow formatting. A custom class inhereting from `SocketHandler` and overriding `emit` to format before pickling did the trick.

```
class FormattedSocketHandler(SocketHandler):
    """ Works in the same way as SocketHandler, but it uses formatters. """

     def emit(self, record):
        """
        Works exactly like SocketHandler.emit but formats the record before sending it.
        record.args is set to none since they are already used by self.format, otherwise makePickle would try to
        use them again and fail.
         Args:
            record (:obj:LogRecord <logging.LogRecord>): the record to be emitted.
        """
        try:
            record.msg = self.format(record)
            record.args = None

             s = self.makePickle(record)
            self.send(s)

         except Exception:
            self.handleError(record)
```
